jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: python -m unittest discover

    - name: Install dependencies
      run: |
        pip install flake8
        pip install -r requirements.txt  # If you have any requirements

    - name: Run linter
      run: flake8 .
      
    - name: Run tests
      run: python -m unittest discover

    - name: Install coverage
      run: pip install coverage

    - name: Run tests with coverage
      run: |
        coverage run -m unittest discover
        coverage report
        coverage xml  # Generates an XML report for CI tools to pick up
